name: Build

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'
          cache: gradle


      - name: Build with Gradle
        run: ./gradlew jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-checking
          path: build/libs/model-checking-1.0-SNAPSHOT.jar